spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC&CharacterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: lixuan
    username: root


